### ISSUE TITLE
Techguns crash with Carianstyle.

### ISSUE THREAD

**Issue by pacjack** [Roinflam/CarianStyle#1]
[crash-2022-05-28_21.03.02-client.txt](https://github.com/Roinflam/CarianStyle/files/8791695/crash-2022-05-28_21.03.02-client.txt)

Idk what the problem is really, but everytime when i shoot there is a chance that i get a crash and has something to do with techguns but idk for sure, can you help?

**Comment by Roinflam** [comment]
Oh sorry i only saw it now, i will try to fix this in the next version.

**Comment by pacjack** [comment]
Ok just take your time, also the mod is great.

**Comment by Roinflam** [comment]
Oh, I think you should approach this author to report the problem. There is a bug in his project rendering related code. There seems to be no problem with my code here.
### techguns-1.12.2-2.0.2.0_pre3.2.jar
